### ISSUE TITLE
suggestion: interop for hexal, sonecutter spell compat with mote records

### ISSUE THREAD

**Issue by Shibva** [SamsTheNerd/HexGloop#78]
the title should be self explanitory; an ability for stonecutter to accept motes and push the finished mote; maybe as stonecutter II spell

**Comment by SamsTheNerd** [comment]
Motes can be retrieved as & stored from item entities, which can be used with this spell. Adding explicit interop would not allow any new/interesting behavior, and I think having to go through that extra layer is both more interesting and better suits hex's design, with emergent interactions rather than explicit interop.
